### ISSUE TITLE
マイグレーションツールを導入する．

### ISSUE THREAD

**Issue by kanekou** [kanekou/comic-app#18]
# 関連issue
#12 

# 背景
現在マイグレーションツールを使わずにDBを作成しているため，修正時にtableごと消したりしている．
実際のデータが入った場合，現実的ではないためマイグレーションツールを導入する．
拡張性のためActiveRocordを使わず，Flywayを採用する．

# 期待される効果
DBjのマイグレーションを管理できる．

**Comment by kanekou** [comment]
マイグレーション用のDockerファイルを作成する，

**Comment by kanekou** [comment]
ローカル上でのマイグレーションはできた．
問題はherokuである．

**Comment by kanekou** [comment]
参考サイト
https://devcenter.heroku.com/ja/articles/running-database-migrations-for-java-apps#using-flyway

**Comment by kanekou** [comment]
一番したのjava flyway APIを採用する．

**Comment by kanekou** [comment]
failした
```
/bin/sh: 1: java: not found
```

**Comment by kanekou** [comment]
javaがないと言われてるのでインストールする必要ありなのかな

**Comment by kanekou** [comment]
jdkとやらを検知した場合は自動でインストール始まるのか．

**Comment by kanekou** [comment]
手動でインストールしたいな

**Comment by kanekou** [comment]
java appのサンプルページをみる
https://devcenter.heroku.com/articles/getting-started-with-java#prepare-the-app

**Comment by kanekou** [comment]
うーん，java単体のインストール，キツそうだな

**Comment by kanekou** [comment]
素直にActive Record使う？

**Comment by kanekou** [comment]
mvnwファイルを入れてみてもダメだった．
javaファイルとして検知されないため，jdkがインストールされない
```
p% git push heroku feature/migration-tool:master
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 3.43 KiB | 1.71 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Ruby app detected
remote: -----> Installing bundler 2.1.4
remote: -----> Removing BUNDLED WITH version in the Gemfile.lock
remote: -----> Compiling Ruby/Rack
remote: -----> Using Ruby version: ruby-2.6.6
remote: -----> Installing dependencies using bundler 2.1.4
remote:        Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
  1 web: bundle exec ruby app.rb -p $PORT
remote:        Using aws-eventstream 1.1.0
remote:        Using aws-partitions 1.385.0
remote:        Using aws-sigv4 1.2.2
remote:        Using jmespath 1.4.0
remote:        Using aws-sdk-core 3.109.1
remote:        Using aws-sdk-kms 1.39.0
remote:        Using aws-sdk-s3 1.83.1
remote:        Using bcrypt 3.1.15
remote:        Using bundler 2.1.4
remote:        Using byebug 11.1.3
remote:        Using coderay 1.1.3
remote:        Using method_source 1.0.0
remote:        Using ruby2_keywords 0.0.2
remote:        Using mustermann 1.1.1
remote:        Using pg 1.2.3
remote:        Using pry 0.13.1
remote:        Using pry-byebug 3.9.0
remote:        Using rack 2.2.3
remote:        Using rack-flash3 1.0.5
remote:        Using rack-protection 2.0.8.1
remote:        Using tilt 2.0.10
remote:        Using sinatra 2.0.8.1
remote:        Bundle complete! 8 Gemfile dependencies, 22 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into `./vendor/bundle`
remote:        Bundle completed (0.38s)
remote:        Cleaning up the bundler cache.
remote: -----> Detecting rake tasks
remote:        Could not detect rake tasks
remote:        ensure you can run `$ bundle exec rake -P` against your app
remote:        and using the production group of your Gemfile.
remote:        /tmp/build_8c0765d0/vendor/ruby-2.6.6/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem rake (>= 0.a) with executable rake (Gem::GemNotFoundException)
remote:        	from /tmp/build_8c0765d0/vendor/ruby-2.6.6/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
remote:        	from /tmp/build_8c0765d0/vendor/ruby-2.6.6/bin/rake:29:in `<main>'
remote:
remote: ###### WARNING:
remote:
remote:        You have not declared a Ruby version in your Gemfile.
remote:
remote:        To declare a Ruby version add this line to your Gemfile:
remote:
remote:        ```
remote:        ruby "2.6.6"
remote:        ```
remote:
remote:        For more information see:
remote:          https://devcenter.heroku.com/articles/ruby-versions
remote:
remote:
remote: -----> Discovering process types
remote:        Procfile declares types     -> release, web
remote:        Default types for buildpack -> console, rake
remote:
remote: -----> Compressing...
remote:        Done: 17.5M
remote: -----> Launching...
remote:  !     Release command declared: this new release will not be available until the command succeeds.
remote:        Released v19
remote:        https://shrouded-castle-37624.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
remote: Running release command...
remote:
remote: /bin/sh: 1: java: not found
remote: Waiting for release.... failed.
To https://git.heroku.com/shrouded-castle-37624.git
   09686c9..abf655a  feature/migration-tool -> master
```

**Comment by kanekou** [comment]
仕方ないので，active recordを導入する．

**Comment by kanekou** [comment]
https://qiita.com/myokkie/items/b6b68b247ec7a110a1c4

**Comment by kanekou** [comment]
Active Recordでuserモデル作成できた
参考サイト: https://github.com/sinatra-activerecord/sinatra-activerecord

**Comment by kanekou** [comment]
migration完了！デプロイできた!

```
% heroku run rake db:migrate
Running rake db:migrate on ⬢ up, run.1825 (Free)
== 20201218071832 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0231s
== 20201218071832 CreateUsers: migrated (0.0233s) =============================

== 20201218073457 CreateComics: migrating =====================================
-- create_table(:comics)
   -> 0.0334s
== 20201218073457 CreateComics: migrated (0.0336s) ============================

== 20201218074731 CreatePages: migrating ======================================
-- create_table(:pages)
   -> 0.0140s
== 20201218074731 CreatePages: migrated (0.0142s) =============================

== 20201218075518 CreateBookmarks: migrating ==================================
-- create_table(:bookmarks)
   -> 0.0226s
-- add_index(:bookmarks, [:user_id, :comic_id])
   -> 0.0039s
== 20201218075518 CreateBookmarks: migrated (0.0268s)
```

**Comment by kanekou** [comment]
おそらく正常に動く
